# Generated by Django 4.0.1 on 2023-10-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_film_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='kind_of_movie',
            field=models.CharField(choices=[('Film dokumentalny', 'Film dokumentalny'), ('Komedia romantyczna', 'Komedia romantyczna'), ('Filmy akcji', 'Filmy akcji'), ('Komedia', 'Komedia'), ('Horror', 'Horror'), ('Dramat', 'Dramat'), ('Fantastyczno-naukowy', 'Fantastyczno-naukowy')], max_length=50, null=True),
        ),
    ]
