# Generated by Django 4.0.1 on 2023-10-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_film_kind_of_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='kind_of_movie',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Dramat', 'Dramat'), ('Fantastyczno-naukowy', 'Fantastyczno-naukowy'), ('Filmy akcji', 'Filmy akcji'), ('Komedia', 'Komedia'), ('Komedia romantyczna', 'Komedia romantyczna'), ('Fantastyczny', 'Fantastyczny'), ('Film dokumentalny', 'Film dokumentalny')], max_length=50, null=True),
        ),
    ]
