# Generated by Django 4.0.1 on 2023-10-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_alter_film_kind_of_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='data_premiere',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='film',
            name='kind_of_movie',
            field=models.CharField(choices=[('Dramat', 'Dramat'), ('Film dokumentalny', 'Film dokumentalny'), ('Horror', 'Horror'), ('Komedia romantyczna', 'Komedia romantyczna'), ('Filmy akcji', 'Filmy akcji'), ('Fantastyczny', 'Fantastyczny'), ('Fantastyczno-naukowy', 'Fantastyczno-naukowy'), ('Komedia', 'Komedia')], max_length=50, null=True),
        ),
    ]
