# Generated by Django 4.0.1 on 2023-10-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_film_data_premiere_alter_film_kind_of_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='kind_of_movie',
            field=models.CharField(choices=[('Komedia', 'Komedia'), ('Fantastyczno-naukowy', 'Fantastyczno-naukowy'), ('Dramat', 'Dramat'), ('Filmy akcji', 'Filmy akcji'), ('Fantastyczny', 'Fantastyczny'), ('Komedia romantyczna', 'Komedia romantyczna'), ('Horror', 'Horror'), ('Film dokumentalny', 'Film dokumentalny')], max_length=50, null=True),
        ),
    ]
