# Generated by Django 4.0.1 on 2023-10-29 12:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myApp', '0007_film_describe_alter_film_kind_of_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='kind_of_movie',
            field=models.CharField(choices=[('Fantastyczno-naukowy', 'Fantastyczno-naukowy'), ('Horror', 'Horror'), ('Komedia romantyczna', 'Komedia romantyczna'), ('Filmy akcji', 'Filmy akcji'), ('Dramat', 'Dramat'), ('Komedia', 'Komedia'), ('Film dokumentalny', 'Film dokumentalny'), ('Fantastyczny', 'Fantastyczny')], max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('film', 'user')},
                'index_together': {('film', 'user')},
            },
        ),
    ]
